### PR TITLE
Change images to quay.io

### PR DESCRIPTION
**Pull request by sandsebi**

### CODE REVIEW

**Comment by sandsebi** [comment]
I have tested all the image changes using the demo branch, unfortunately the runs are in my personal workspace.
Here are the screenshots from there:
image
image

**Review by davidyuyuan — CHANGES_REQUESTED** [review]
Please tag all the images in quay.io. For contiuation, please use the same tags to indicate we only changed the repositories and the images are the same.

**Comment by davidyuyuan** [comment]
We don't have CI/CD pipelines to build the images, do we?

**Comment by sandsebi** [comment]
What tags do you want these images to have? I thought we could add a new tag when we make a change to these images.
With respect to CI/CD, no we don't have a way at the moment. 
I can try and see how we can add a way.

**Comment by davidyuyuan** [comment]
I thought that we did not change the content of the images. You just moved them to different repositories. If you have made changes, please tag them with higher versions. If not, please keep the same version.
Yanisa uses git actions to build images. I have never coded with that but just reviewed her implementation. Please ask her to send you a link to the YAML as well as API docs.

**Comment by sandsebi** [comment]
That is correct. I have not made changes, just moved them over.
Okay I'll keep the same version numbers and amend this change. 
Thanks I'll reach out to Yanisa if needed 👍

**Comment by sandsebi** [comment]
I've tested the changes with the tagged versions. 
Works fine, you can see the runs on the shared namespace.

**Review by davidyuyuan — APPROVED** [review]

**Pull request merged**
