### PR TITLE
Changes to submit .vcf and .coverage separately in a new project for …

### PR DESCRIPTION
**Pull request by sandsebi**
…ELTE

### CODE REVIEW

**Comment by davidyuyuan** [comment]
There are two potential problems:

1. There is no implementation in illumina.nf
2. The lines 37 would submit to the public data hub instead of the private data hub for ELTE. You need to use different webin ID and password from Coleman.
3. To make #2 working, the password file gs://prj-int-dev-covid19-nf-gls/data/projects_accounts.csv needs to be updated. The new row needs to be read to get the ID and password.

**Comment by sandsebi** [comment]
Thanks for the comments. I will surely add the steps for Illumina as well.
I clarified with Colman and the same credentials that we use for the project - `PRJEB45555` can be used for this new project as well, hence I added the code within the same block.
I'll add a comment to explain this.
He also mentioned that ELTE will use credentials to download the data, from a submission perspective we don't need to.
Suran has created a ticket to add authentication to the downloader tool.

**Comment by davidyuyuan** [comment]
Thanks for the clarification on #2 and 3. This PR needs to be done ASAP. Please ask Colman / Nadim to review the objects submitted on the test server. We can coordinate the merge of the PR and for Milena to pull the changes in the next batch.

**Comment by davidyuyuan** [comment]
All changes look good to me. Once the analysis objects are reviewed on the test server, please merge this PR.

**Pull request merged**
